.\" Manpage for microterm.
.TH MICROTERM "08" "April 2024" "microterm" "User Commands"
.SH NAME
microterm \- (µterm) Simple VTE-based GTK terminal emulator
.SH SYNOPSIS
.B microterm
[options]
.SH DESCRIPTION
microterm is a simple VTE-based GTK terminal emulator inspired by kermit.
.SH RELEASE
Current release: 2.2
.SH OPTIONS
.TP
\fB\-c\fR <PATH>
set the configuration file
.TP
\fB\-t\fR <TITLE>
set the terminal title
.TP
\fB\-w\fR <DIR>
set the working directory
.TP
\fB\-e\fR <CMD>
set the command to run
.TP
\fB\-d\fR
activate debug messages
.TP
\fB\-v\fR
show version
.TP
\fB\-h\fR
show help
.SH BINDINGS
Bindings in microterm are defined in configuration file with the parameter hotkey:
.TP
\fBhotkey key_binding function\fR
.TP
Key binding is a sequence of keyboard button separated by a plus sign (+).
.SH FUNCTIONS
Valid functions are:
.TP
\fBcopy\fR: copy selected text to clipboard
.TP
\fBpaste\fR: paste from clipboard
.TP
\fBreload\fR: reload configuration file
.TP
\fBquit\fR: close the application (close all terminals)
.TP
\fBfont_inc\fR: increase font size
.TP
\fBfont_dec\fR: decrease font size
.TP
\fBfont_reset\fR: reset font size to default
.TP
\fBsplit_v\fR: split vertically with a new terminal on bottom
.TP
\fBsplit_h\fR: split horizzontally with a new terminal on right
.TP
\fBnew_tab\fR: open a new terminal in a new tab
.TP
\fBprev\fR: switch to the previous tab
.TP
\fBnext\fR: switch to the next tab
.TP
\fBclose\fR: close selected tab
.TP
\fBgoto <n>\fR: go to specified tab
.TP
\fBexec <command>\fR: send specified command to current terminal and execute (press return)
.TP
\fBcmd\fR: open command prompt

.SH CONFIGURATION FILE
microterm search for configuration file stored in $HOME/.config/microterm/microterm.conf
.TP
Parameter for configuration file:
.TP
\fBlocale\fR <LOCALE>
set terminal locale to use, default value: "en_US.UTF-8"
.TP
\fBchar\fR <CHAR_LIST>
set VTE word chars list exception, default value: "-./?%&#_=+@~"
.TP
\fBtab\fR <bottom|top>
set tab position, accepted values are bottom or top, default: top
.TP
\fBcommander\fR <bottom|top>
set commander position, accepted values are bottom or top, default: bottom
.TP
\fBcopy_on_selection\fR <true|false>
enable copy on text selection in terminal, accepted values are true or false, default: true
.TP
\fBfocus_follow_mouse\fR <true|false>
set to true for change focus based on mouse position, accepted values are true or false, default: false
.TP
\fBfont\fR <FONT_NAME> <SIZE>
set terminal font to specified font name and size, default: Monospace 9
.TP
\fBopacity\fR <0.00 to 1.00>
set terminal opacity, accept any value from 0.00 to 1.00, default: 1.00
.TP
\fBcursor_shape\fR <underline|beam|block>
set the cursor sharep in terminal, accepted values are underline or beam or, default: block
.TP
\fBcursor\fR <COLOR>
set terminal cursor color, RGBA color, default: 0xffffff
.TP
\fBcursor_foreground\fR <COLOR>
set terminal cursor foreground color, RGBA color, default: 0xffffff
.TP
\fBforeground\fR <COLOR>
set terminal foreground color, RGBA color, default: 0xffffff
.TP
\fBforeground_bold\fR <COLOR>
set terminal foreground color for bold text, RGBA color, default: 0xffffff
.TP
\fBbackground\fR <COLOR>
set terminal background color, RGBA color, default: 0x000000
.TP
\fBcolor<0-15>\fR <COLOR>
set 16 color scheme value, RGBA color
.TP
\fBhotkey\fR <key binding plus separated> <function>
set the hotkey on terminal, when combination of defined hotkey buttons are pressed 
the function will be executed
.TP
\fBinclude\fR <FILE_NAME>
load the content of specified file. The file must be in the configuration directory.

.SH BUGS
No known bugs.
Use "Issues" page for reporting bugs: <https://github.com/BlackCodec/microterm/issues/>

.SH AUTHOR
Written by Fabio Dell'Orso (Black_Codec) <blackcodec@null.net>

.SH COPYRIGHT
Copyright © 2024 Fabio Dell'Orso
.P
GNU General Public License v3.0 only
